#include "variant.h"

/*
* Pins descriptions
*/
const PinDescription g_APinDescription[] =
{
	// 0..13 - Digital pins
	{PORTA,0,PIO_DIGITAL,(PIN_ATTR_DIGITAL),No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_0}, 							// D0 - G4	// XTAL / IO pad - M48
	{PORTA,1,PIO_DIGITAL,(PIN_ATTR_DIGITAL),No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_1}, 							// D1 - G5	// XTAL / IO pad - M73
	{PORTA,27,PIO_DIGITAL,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_15}, 							// D2 - G6			- M71
	{PORTB,15,PIO_SERCOM,(PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM5_CH1,NOT_ON_TIMER,EXTERNAL_INT_15},					// D3 - G10			- M63
	{PORTA,13,PIO_SERCOM,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM),No_ADC_Channel,PWM0_CH5,NOT_ON_TIMER,EXTERNAL_INT_13}, 				// D4 - SS1			- M67
	{PORTA,12,PIO_SERCOM,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_12}, 								// D5 - MISO1		- M65
	{PORTA,28,PIO_COM,PIN_ATTR_NONE,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_NONE}, 									// D6 - I2C_INT		- M16
	{PORTA,20,PIO_TIMER_ALT,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER_ALT),No_ADC_Channel,PWM0_CH6,TCC0_CH6,EXTERNAL_INT_4}, // D7 - TX1	- M17
	{PORTA,21,PIO_TIMER_ALT,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER_ALT),No_ADC_Channel,PWM0_CH7,TCC0_CH7,EXTERNAL_INT_5}, // D8 - RX1	- M19
	{PORTA,22,PIO_SERCOM,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_6}, 								// D9  - SDA		- M12
	{PORTA,23,PIO_SERCOM,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_7}, 								// D10 - SCL		- M14
	{PORTA,14,PIO_SERCOM,(PIN_ATTR_DIGITAL),No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_14},							// D11 - MOSI1		- M53
	{PORTA,15,PIO_SERCOM,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM3_CH1,TC3_CH1,EXTERNAL_INT_15}, 	// D12 - SCK1		- M51
	{PORTA,17,PIO_PWM,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM2_CH1,TCC2_CH1,EXTERNAL_INT_1}, 		// D13 - LED 		- M52

	// 14..33 - Analog pins
	{PORTA,2,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel0,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_2}, 									// D14/A0 -  A0/DAC	- M34
	{PORTA,4,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel4,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_4}, 									// D15/A1 -  A1		- M38
	{PORTA,7,PIO_ANALOG,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel7,PWM1_CH1,TCC1_CH1,EXTERNAL_INT_7}, 		// D16/A2 -  Vin/3	- M49
	{PORTA,9,PIO_SERCOM,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel17,PWM0_CH1,TCC0_CH1,EXTERNAL_INT_9}, 	// D17/A3 -  SCK	- M57
	{PORTA,11,PIO_SERCOM,(PIN_ATTR_DIGITAL | PIN_ATTR_ANALOG),ADC_Channel19,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_11},			// D18/A4 -  MISO	- M61
	{PORTA,6,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel6,PWM1_CH0,TCC1_CH0,EXTERNAL_INT_6},		// D19/A5 -			- M42
	{PORTA,5,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel5,PWM0_CH1,NOT_ON_TIMER,EXTERNAL_INT_5},										// D20/A6 -  G0		- M40
	{PORTA,8,PIO_SERCOM,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel16,PWM0_CH0,TCC0_CH0,EXTERNAL_INT_NMI},  	// D21/A7 -  MOSI	- M59
 	{PORTB,4,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel12,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_5},							 		// D22/A8 -  D1		- M18
 	{PORTB,5,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel13,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_5},							 		// D23/A9 - 3.3V EN	- M4
 	{PORTB,6,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel14,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_5},							 		// D24/A10 - CAN RX	- M41
 	{PORTB,7,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel15,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_5},							 		// D25/A11 - CAN TX	- M43
	{PORTA,3,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel1,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_3},									// D26/A12 - D0		- M10
	{PORTB,8,PIO_ANALOG,(PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel2,PWM4_CH0,TC4_CH0,EXTERNAL_INT_8},							// D27/A13 - G2		- M44
	{PORTB,9,PIO_ANALOG,(PIN_ATTR_PWM | PIN_ATTR_TIMER),ADC_Channel3,PWM4_CH1,TC4_CH1,EXTERNAL_INT_9},							// D28/A14 - G3		- M46
	{PORTA,10,PIO_SERCOM,(PIN_ATTR_DIGITAL),ADC_Channel18,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_10}, 							// D29/A15 - CS		- M55
	{PORTB,3,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel11,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_3},									// D30/A16 - SDIO_D3- M70
	{PORTB,2,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel10,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_2}, 									// D31/A17 - SDIO_D2- M68
	{PORTB,1,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel9,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_1}, 									// D32/A18 - SDIO_D1- M66
	{PORTB,0,PIO_ANALOG,PIN_ATTR_ANALOG,ADC_Channel8,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_0}, 									// D33/A19 - SDIO_D0- M64

	// 34..49	 Digital pins
	{PORTA,16,PIO_SERCOM,PIN_ATTR_NONE,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_NONE}, 								// D34 - AUD_BCLK	- M50
 	{PORTA,18,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM3_CH0,TC3_CH0,EXTERNAL_INT_2}, 	// D35 - CTS1		- M15
	{PORTA,19,PIO_TIMER_ALT,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER_ALT),No_ADC_Channel,PWM0_CH3,TCC0_CH3,EXTERNAL_INT_3}, // D36 - RTS1	- M13
	{PORTA,30,PIO_PWM,PIN_ATTR_DIGITAL | PIO_SERCOM,No_ADC_Channel,NOT_ON_PWM,TCC1_CH0,EXTERNAL_INT_10}, 						// D37 - SWCLK		- M21
	{PORTA,31,PIO_PWM,PIN_ATTR_DIGITAL | PIO_SERCOM,No_ADC_Channel,NOT_ON_PWM,TCC1_CH1,EXTERNAL_INT_11}, 						// D38 - SWDIO		- M23
	{PORTB,22,PIO_SERCOM_ALT,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM),No_ADC_Channel,PWM7_CH0,NOT_ON_TIMER,EXTERNAL_INT_6}, 			// D39 - TX2		- M20
	{PORTB,23,PIO_SERCOM_ALT,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM),No_ADC_Channel,PWM7_CH1,NOT_ON_TIMER,EXTERNAL_INT_7},			// D40 - RX2		- M22
 	{PORTB,31,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM0_CH1,TCC1_CH3,EXTERNAL_INT_14}, 	// D41 - SDIO_CMD	- M62
 	{PORTB,30,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM0_CH0,TCC1_CH2,EXTERNAL_INT_15}, 	// D42 - SDIO_SCK	- M60
 	{PORTB,17,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM0_CH0,TCC1_CH2,EXTERNAL_INT_15}, 	// D43 - AUD_MCK	- M58
 	{PORTB,16,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM0_CH0,TCC1_CH2,EXTERNAL_INT_15}, 	// D44 - AUD_OUT	- M56
	{PORTB,14,PIO_SERCOM_ALT,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_14},							// D45 - G11		- M8
	{PORTB,13,PIO_SERCOM_ALT,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_13},							// D46 - G7			- M69
 	{PORTB,12,PIO_TIMER,(PIN_ATTR_DIGITAL | PIN_ATTR_PWM | PIN_ATTR_TIMER),No_ADC_Channel,PWM0_CH0,TCC1_CH2,EXTERNAL_INT_15}, 	// D47 - AUD_IN		- M54
	{PORTB,11,PIO_SERCOM_ALT,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_11},							// D48 - PWM1		- M47
	{PORTB,10,PIO_SERCOM_ALT,PIN_ATTR_DIGITAL,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_10},							// D49 - CE_NRF		- M32

	// 50..51 - USB
	// --------------------
	{PORTA,24,PIO_COM,PIN_ATTR_NONE,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_NONE}, // USB/DM						// D50 				- M5
	{PORTA,25,PIO_COM,PIN_ATTR_NONE,No_ADC_Channel,NOT_ON_PWM,NOT_ON_TIMER,EXTERNAL_INT_NONE}, // USB/DP						// D51 				- M3
};

extern "C" {
	unsigned int PINCOUNT_fn() {
		return (sizeof(g_APinDescription) / sizeof(g_APinDescription[0]));
	}
}

const void* g_apTCInstances[TCC_INST_NUM + TC_INST_NUM] = {TCC0,TCC1,TCC2,TC3,TC4,TC5};

// Multi-serial objects instantiation
SERCOM sercom0(SERCOM0);			// Serial1
SERCOM sercom1(SERCOM1);			// Serial3
SERCOM sercom2(SERCOM2);			// SPI
SERCOM sercom3(SERCOM3);			// I2C
SERCOM sercom4(SERCOM4);			// SPI1
SERCOM sercom5(SERCOM5);			// Serial2

Uart Serial1(&sercom5, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX, UPIO_SERCOM);

void SERCOM5_Handler()
{
	Serial1.IrqHandler();
}

Uart Serial2(&sercom0, PIN_SERIAL2_RX, PIN_SERIAL2_TX, PAD_SERIAL2_RX, PAD_SERIAL2_TX, UPIO_SERCOM);

void SERCOM0_Handler()
{
	Serial2.IrqHandler();
}
